DELETE http://localhost:3003/api/blogs/63f9b183fa5be8c60f1ab66e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJ5ZW5vdyIsImlkIjoiNjNmOWIxYmVmYTViZThjNjBmMWFiNjczIiwiaWF0IjoxNjc3MzA4NDQ5fQ.qQWapbYerVDIUSqGA_tVlLDegPKpcwd2UmSarvaxVLM